### PR TITLE
universal-hash v0.1.0

### PR DESCRIPTION
**Pull request by tarcieri**
Initial release

### CODE REVIEW

**Comment by tarcieri** [comment]
@newpavlov dunno if I'll be able to push the tag, but will publish when it's green

**Comment by tarcieri** [comment]
@newpavlov also are you going to push an initial commit to https://github.com/RustCrypto/universal-hashes or should I?

**Comment by newpavlov** [comment]
I will add a tag here and right after publishing. You can do a first commit to the universal-hashes repo.

**Comment by tarcieri** [comment]
Sounds good! I'll push an initial commit to https://github.com/RustCrypto/universal-hashes and then open PRs to move `poly1305` and `polyval` over.

**Comment by newpavlov** [comment]
Since it's a simple move, I think you can commit crates directly.

**Comment by tarcieri** [comment]
Alright, will do that, then open PRs to move them over to the `UniversalHash` trait.

**Pull request merged**
