### PR TITLE
digest v0.11

### LINKED ISSUE #1027: Duplication / confusion between `KeyInit::new` and `digest::Mac::new`
The `Mac::new` trait is defined as:

```rust
    fn new(key: &Key<Self>) -> Self
    where
        Self: KeyInit;
```

...but it provides no default definition, requires `Self` impl `KeyInit`, and causes ambiguity:

```
error[E0034]: multiple applicable items in scope
   --> aes-siv/src/siv.rs:81:22
    |
81  |         let mac = M::new(GenericArray::from_slice(&key[..M::KeySize::to_usize()]));
    |                      ^^^ multiple `new` found
    |
note: candidate #1 is defined in the trait `KeyInit`
   --> /Users/tony/.cargo/registry/src/github.com-1ecc6299db9ec823/crypto-common-0.1.3/src/lib.rs:115:5
    |
115 |     fn new(key: &Key<Self>) -> Self;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `Mac`
   --> /Users/tony/.cargo/registry/src/github.com-1ecc6299db9ec823/digest-0.10.3/src/mac.rs:21:5
    |
21  | /     fn new(key: &Key<Self>) -> Self
22  | |     where
23  | |         Self: KeyInit;
    | |______________________^
help: disambiguate the associated function for candidate #1
```

### PR DESCRIPTION
**Pull request by newpavlov**
Depends on https://github.com/RustCrypto/traits/pull/1172 and https://github.com/RustCrypto/utils/pull/823

Closes #1027

### Changed
- `crypto-common` dependency bumped to v0.2
- Edition changed to 2021 and MSRV bumped to 1.57

### Removed
- `Mac::new`, `Mac::new_from_slice`, and `Mac::generate_key` methods

### CODE REVIEW

**Comment by newpavlov** [comment]
@tarcieri 
Regarding #1027. Do you think we should simply remove `Mac::new` and instead tell users to rely on `KeyInit::new`?

**Comment by tarcieri** [comment]
@newpavlov yes, sounds good to me

**Comment by tarcieri** [comment]
It'd probably also be good to leave this at `-pre` too to allow additional breaking changes (like a `hybrid-array` migration)

**Comment by newpavlov** [comment]
I temporarily removed `-pre` to make it easier to prototype https://github.com/RustCrypto/hashes/pull/444.

**Pull request merged**
