### PR TITLE
Pin subtle to v2.4 for crypto-mac v0.11

### PR DESCRIPTION
**Pull request by newpavlov**
#690 has pinned `subtle` for `crtypto-mac` v0.10.

### CODE REVIEW

**Comment by newpavlov** [comment]
The clippy warning is irrelevant for changes in this PR.

**Comment by bridiver** [comment]
was there a specific reason for this? We needed to bump subtle to 2.6 and it ended up taking us back to 0.11.0 from 0.11.1

**Comment by newpavlov** [comment]
It was done in an attempt to preserve MSRV of the crate. Later we found this approach to be flawed and no longer use it.

I would suggest to update your dependencies. `crypto-mac` was deprecated a fair time ago.

**Comment by bridiver** [comment]
> I would suggest to update your dependencies. `crypto-mac` was deprecated a fair time ago.

I wish it were that easy when dealing with transitive dependencies in rust crates, but thanks for the info!

**Comment by tarcieri** [comment]
@bridiver out of curiosity, which crate is still using `crypto-mac`?

**Comment by bridiver** [comment]
> @bridiver out of curiosity, which crate is still using `crypto-mac`?

We have several long chains of deps actually

fvm_shared 0.7 -> libsecp256k1 0.7 -> hmac_drbg 0.3 -> hmac 0.8 -> crypto_hmac 0.8
fvm_shared 0.7 -> bls-signatures 0.15 -> hkdf 0.11 -> hmac 0.11 -> crypto_hmac 0.11

**Comment by tarcieri** [comment]
`hmac-drbg` looks abandoned, having not received updates in over 4 years.

Perhaps we should consider moving the HMAC-DRBG implementation in the `rfc6979` crate into the `hmac` crate so others can use it? /cc @newpavlov 

It's unfortunate `bls-signatures` has not updated to a newer version of `hkdf`

**Comment by newpavlov** [comment]
I think we can create a new HMAC-DRBG crate in the CSPRNs repo.

**Pull request merged**
