### PR TITLE
Committing AEAD marker traits and generic constructions

### PR DESCRIPTION
**Pull request by rlee287**
See the documentation comments for an explanation of committing AE and the generic constructions included.

### CODE REVIEW

**Comment by rlee287** [comment]
Seems like the test failures are caused by the cipher crate emitting a warning in the minimal version build, as opposed to being related to any of the changes I made.

**Comment by newpavlov** [comment]
I think it will be better to move the wrapper into a different crate in the AEADs repository and link it in the new wrappers trait docs.

**Comment by tarcieri** [comment]
Yeah, I had a similar first thought: this might make sense in a separate crate.

If it were located in the https://github.com/RustCrypto/AEADs/ repo it would be much easier to test the generic implementation against a concrete AEAD algorithm implementation located there.

**Comment by rlee287** [comment]
I'll move the wrappers into a separate PR to the AEADs repo, but I'll also take the time to add some tests using concrete AEADs. However, I'd like to confirm whether you think it'd be better to keep the marker traits in the `aead` crate of this repo or whether I should also move the traits into the separate crate as well.

**Comment by rlee287** [comment]
I opened a PR against the AEADs repo at https://github.com/RustCrypto/AEADs/pull/564, so I'll close this one. I will send in a PR to cross-reference the new crate in the `aead` crate documentation after that one is merged.

**Comment by tarcieri** [comment]
Sounds good. Since committing AEADs can be completely implemented in that crate, it seems like there isn't much value in having upstream marker traits?

We're going to start making breaking changes to `aead` soon, so if there's anything you do need changed, get a PR in ASAP

**Pull request closed without merging**
