### PR TITLE
Implement `ZeroizeOnDrop` on appropriate items

### PR DESCRIPTION
**Pull request by daxpedda**
I'm assuming this is a breaking change.

### CODE REVIEW

**Comment by tarcieri** [comment]
You'll need to bump the `zeroize` dependency to 1.5 in order for this to work.

Other than that it shouldn't be a breaking change.

**Comment by daxpedda** [comment]
I already had in `Cargo.lock`, I assumed you meant in `Cargo.toml`, done that now.

**Comment by daxpedda** [comment]
If I realized that it wasn't a breaking change, I would have said something before the release.

**Comment by tarcieri** [comment]
Thanks!

**Comment by tarcieri** [comment]
> Any chance we can still get this out?

I can cut one more release of `elliptic-curve` v0.11 prior to landing #883

**Comment by tarcieri** [comment]
`elliptic-curve` v0.11.8 released in #889

**Pull request merged**
