### PR TITLE
Digest v0.8

### PR DESCRIPTION
**Pull request by newpavlov**

### CODE REVIEW

**Comment by newpavlov** [comment]
I think I am fairly close to that I wanted to achieve with v0.8. Can you share your timetable?

**Comment by ignatenkobrain** [comment]
No particular timeline, just wanted to package warp framework and one of deps is this project :)

So the answer would be: as soon you have time.

**Comment by newpavlov** [comment]
Yes, hopefully in a week or two.

**Comment by kpcyrd** [comment]
Also interested here from debian-rust :) digest is a dependency of the sha2 crate (also maintained by RustCrypto), so a release of the sha2 crate afterwards would be great!

**Comment by newpavlov** [comment]
Sorry for the delay! Currently this PR is blocked on this [PR](https://github.com/dalek-cryptography/subtle/pull/33), plus I want to simplify test vector format a bit.

**Comment by newpavlov** [comment]
This PR looks more or less ready to me. I'll leave it for several days to see if there will be improvement suggestions. After that I will publish updates to crates.io.

**Pull request merged**
