### PR TITLE
crypto-common: use `core::error::Error` trait; MSRV 1.81

### PR DESCRIPTION
**Pull request by tarcieri**
The `core::error::Error` trait is now stable, meaning we no longer need to gate impls for it on a `std` feature.

### CODE REVIEW

**Comment by tarcieri** [comment]
Also, perhaps we should consider removing the `std` feature entirely from these crates unless it's actually used for things like filesystem access that truly need `std`.

Right now `crypto-common` has the following in its `[features]` section of Cargo.toml:

```toml
std = ["getrandom?/std", "rand_core?/std"]
```

I didn't remove it to keep the change minimal for now, but it's something we could do potentially. I don't think the transitive activation of the `std` features of those crates really helps when using them with `crypto-common`.

**Comment by newpavlov** [comment]
I would really like to migrate to `core::error::Error`, but MSRV 1.81 is too aggressive in my opinion, so I think we should wait until the next release cycle.

**Comment by tarcieri** [comment]
Okay, will leave this as-is and we can take a look again when 1.82 is released (October 17th)

**Comment by sorairolake** [comment]
If this is merged, will you make similar changes to crates in other repositories owned by [RustCrypto](https://github.com/RustCrypto)?

**Comment by newpavlov** [comment]
Yes, we will apply similar changes (including MSRV bump) to our downstream crates as well. Since https://github.com/RustCrypto/hybrid-array/pull/85 has already landed, we are likely to move forward with this change.

**Review by newpavlov — APPROVED** [review]

**Pull request merged**
