### PR TITLE
Make PublicKey::from_encoded_point go through PublicKey::from_affine

### LINKED ISSUE #415: PublicKeys can be zero
Re the recent changes, I tried this code in `p256` and it failed (i.e., it didn't panic)

```rust
#[should_panic]
#[test]
fn zero_pubkey() {
    PublicKey::from_sec1_bytes(&[0]).unwrap();
}
```

This is because `PublicKey::from_encoded_point` doesn't use the identity-sensitive `PublicKey::from_affine` method. I'm sending a PR right now to fix this

### PR DESCRIPTION
**Pull request by rozbb**
Fixes #415

### CODE REVIEW

**Comment by rozbb** [comment]
It's hard to add a regression test for this, because there are no concrete curves we can use to run a test

**Comment by tarcieri** [comment]
It'd be fantastic if you could add a regression test for this as well

**Comment by rozbb** [comment]
One way to allow for a regression test is to pull in a curve like `p256` just for this test. Might be overkill though, and it's a bit circular

**Comment by tarcieri** [comment]
@rozbb yeah this is something of an ongoing problem... no worries!

I have a "mock curve" in the `ecdsa` crate but not in this one.

Perhaps I should move it to this crate (e.g. in a `dev` module) and then the `ecdsa` crate could reuse it.

**Pull request merged**
