### PR TITLE
digest: add block-level API

### PR DESCRIPTION
**Pull request by newpavlov**
This PR exposes block-level API and adds a wrapper type which implements the higher-level traits. It allows to remove some of boilerplate from the implementation crates, plus we no longer need the macro for implementing `io::Read`. Also it will allow a more efficient HMAC implementation.

Additionally PR removes the variable length API in favor of making type generic over output length as suggested in #262.

### CODE REVIEW

**Comment by newpavlov** [comment]
@tarcieri 
I wonder if we can remove the non-core dirty traits.

**Review by tarcieri — APPROVED** [review]
Seems like a nice improvement!

**Comment by jplatte** [comment]
What's the status of this? It seems like it's the only major change holding back releases of digest and blake2 (https://github.com/RustCrypto/hashes/pull/198).

**Comment by newpavlov** [comment]
@jplatte 
I wanted to implement block stream cipher trait for `XofReaderCore` to solve RustCrypto/hashes#181, but unfortunately I couldn't find a good block API for stream ciphers (see #444 for the most recent issue). I probably will simply omit it for now, so `digest v0.10` will not be blocked on release of `cipher v0.3`.

**Pull request merged**
