### PR TITLE
Update VOPRF identifier type

### PR DESCRIPTION
**Pull request by daxpedda**
See https://github.com/cfrg/draft-irtf-cfrg-voprf/pull/371.
We should probably at least wait until this is merged upstream.

Cc @kevinlewi.

### CODE REVIEW

**Comment by tarcieri** [comment]
@daxpedda I think this is good to go now? (aside from the merge conflicts)

**Comment by daxpedda** [comment]
Yes, this was added to VOPRF in draft 17, so this is good to go now.

**Comment by daxpedda** [comment]
Gonna rebase it.

**Comment by daxpedda** [comment]
Fixed the links to point to the new section now and rebased.

**Pull request merged**
